[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "10.15.3"


[dev]
  command = "yarn run start"


[[redirects]]
  from = "/images/tiny/*"
  to = "/.netlify/images/?w=20&fit=cover&url=/images/:splat"
  status = 200
  
  [[redirects]]
  from = "/images/smallsmall/*"
  to = "/.netlify/images/?w=250&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/small/*"
  to = "/.netlify/images/?w=500&fit=cover&url=/images/:splat"
  status = 200
  
  [[redirects]]
  from = "/images/smallmedium/*"
  to = "/.netlify/images/?w=650&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/medium/*"
  to = "/.netlify/images/?w=700&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/large/*"
  to = "/.netlify/images/?w=800&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/original/*"
  to = "/.netlify/images/?url=/images/:splat"
  status = 200
